project2: main.cpp daneEiTI.cpp instytut.cpp interfejs.cpp jednostkiOrganizacyjne.cpp pracownicy.cpp wydzial.cpp zaklad.cpp daneEiTI.h instytut.h interfejs.h jednostkiOrganizacyjne.h pracownicy.h wydzial.h zaklad.h stanowiskaDydaktyczne.h tytulyNaukowe.h
	g++ -std=c++11 main.cpp daneEiTI.cpp instytut.cpp interfejs.cpp jednostkiOrganizacyjne.cpp pracownicy.cpp wydzial.cpp zaklad.cpp

clean:
	rm a.out

open:
	./a.out

